// Scan the codebase for user-facing Arabic strings and write the complete
// translation catalog to lib/i18nCatalog.ts. This guarantees the CSV export
// contains EVERY string in the system, with nothing left out.
//
//   node scripts/extractI18n.js
//
// It collects Arabic string literals ("...", '...', `...` without ${}) and the
// Arabic text inside t("...") calls, across app/, components/ and lib/.
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DIRS = ["app", "components", "lib"];
const EXCLUDE_FILES = new Set([path.join(ROOT, "lib", "i18nCatalog.ts")]);
const ARABIC = /[؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿]/;

function walk(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (["node_modules", ".next", ".git"].includes(entry.name)) continue;
      walk(p, out);
    } else if (/\.(ts|tsx)$/.test(entry.name) && !EXCLUDE_FILES.has(p)) {
      out.push(p);
    }
  }
}

// Strip // line comments and /* */ block comments (rough, string-aware enough
// to avoid dropping quotes inside strings on the same line is overkill here —
// comments with Arabic are just excluded from the catalog).
function stripComments(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/(^|[^:])\/\/[^\n]*/g, (m, p1) => p1);
}

function unescape(s, quote) {
  return s
    .replace(/\\n/g, "\n")
    .replace(/\\t/g, "\t")
    .replace(/\\r/g, "")
    .replace(new RegExp("\\\\" + quote, "g"), quote)
    .replace(/\\\\/g, "\\");
}

// Reject code-like captures (only keep genuine single-line UI strings).
function isUiString(s) {
  if (!s || !ARABIC.test(s)) return false;
  if (s.length > 200) return false;
  if (/[\n\r{}<>]|=>|\breturn\b|className/.test(s)) return false;
  return true;
}

const arabicLetters = (s) => (s.match(/[؀-ۿ]/g) || []).length;

// Convert an interpolated string into a translation TEMPLATE by replacing each
// ${...} or {...} with a sequential {0},{1},… placeholder. Returns the template
// only if it carries real Arabic wording around the placeholders (so patterns
// aren't dangerously generic). `re` is the interpolation syntax to replace.
function toTemplate(raw, re) {
  let i = 0;
  const tpl = raw.replace(re, () => `{${i++}}`).trim();
  if (i === 0) return null; // no placeholders
  if (tpl.length > 200) return null;
  // Reject code-ish captures (nested ternaries, template literals, JSX expr).
  if (/[`$"?\\]|=>|className|\breturn\b|[\n\r<>]/.test(tpl)) return null;
  const residual = tpl.replace(/\{\d+\}/g, "");
  if (/[{}]/.test(residual)) return null; // stray braces => not clean text
  const staticPart = tpl.replace(/\{\d+\}/g, " ");
  if (arabicLetters(staticPart) < 2) return null; // too generic to match safely
  return tpl;
}

function collect(src, found, templates) {
  const reDq = /"((?:[^"\\]|\\.)*)"/g;
  const reSq = /'((?:[^'\\]|\\.)*)'/g;
  const reTpl = /`((?:[^`\\]|\\.)*)`/g; // template literals
  const reJsx = />([^<>{}\n]+)</g; // JSX static text between tags
  const reJsxTpl = />([^<>\n]*\{[^<>\n]*)</g; // JSX text WITH {expr} interpolation
  let m;
  while ((m = reDq.exec(src))) { const v = unescape(m[1], '"').trim(); if (isUiString(v)) found.add(v); }
  while ((m = reSq.exec(src))) { const v = unescape(m[1], "'").trim(); if (isUiString(v)) found.add(v); }
  while ((m = reTpl.exec(src))) {
    const body = m[1];
    if (body.includes("${")) {
      const t = toTemplate(unescape(body, "`"), /\$\{[^}]*\}/g);
      if (t) templates.add(t);
    } else {
      const v = unescape(body, "`").trim();
      if (isUiString(v)) found.add(v);
    }
  }
  while ((m = reJsx.exec(src))) { const v = m[1].trim(); if (isUiString(v)) found.add(v); }
  // JSX runs containing {expr} → templates (e.g. "صفحة {page} من {total}").
  while ((m = reJsxTpl.exec(src))) {
    const t = toTemplate(m[1], /\{[^}]*\}/g);
    if (t) templates.add(t);
  }
}

const files = [];
for (const d of DIRS) {
  const dir = path.join(ROOT, d);
  if (fs.existsSync(dir)) walk(dir, files);
}

const found = new Set();
const templates = new Set();
for (const f of files) collect(stripComments(fs.readFileSync(f, "utf8")), found, templates);

const list = [...found].filter((s) => s && ARABIC.test(s)).sort((a, b) => a.localeCompare(b, "ar"));
// Keep templates out of the static list; sort them too.
const tpls = [...templates].filter((s) => s && ARABIC.test(s)).sort((a, b) => a.localeCompare(b, "ar"));

const out =
  "// AUTO-GENERATED by scripts/extractI18n.js — do not edit by hand.\n" +
  "// The complete list of translatable source (Arabic) strings in the system.\n" +
  "// CATALOG = static strings; TEMPLATES = interpolated patterns with {0},{1},…\n" +
  `export const CATALOG: string[] = ${JSON.stringify(list, null, 2)};\n\n` +
  `export const TEMPLATES: string[] = ${JSON.stringify(tpls, null, 2)};\n`;

fs.writeFileSync(path.join(ROOT, "lib", "i18nCatalog.ts"), out);
console.log(`i18n catalog: ${list.length} strings + ${tpls.length} templates from ${files.length} files.`);
