// Scan the codebase for user-facing Arabic strings and write the complete
// translation catalog to lib/i18nCatalog.ts. This guarantees the CSV export
// contains EVERY string in the system, with nothing left out.
//
//   node scripts/extractI18n.js
//
// It collects Arabic string literals ("...", '...', `...` without ${}) and the
// Arabic text inside t("...") calls, across app/, components/ and lib/.
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DIRS = ["app", "components", "lib"];
const EXCLUDE_FILES = new Set([path.join(ROOT, "lib", "i18nCatalog.ts")]);
const ARABIC = /[؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿]/;

function walk(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (["node_modules", ".next", ".git"].includes(entry.name)) continue;
      walk(p, out);
    } else if (/\.(ts|tsx)$/.test(entry.name) && !EXCLUDE_FILES.has(p)) {
      out.push(p);
    }
  }
}

// Strip // line comments and /* */ block comments (rough, string-aware enough
// to avoid dropping quotes inside strings on the same line is overkill here —
// comments with Arabic are just excluded from the catalog).
function stripComments(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/(^|[^:])\/\/[^\n]*/g, (m, p1) => p1);
}

function unescape(s, quote) {
  return s
    .replace(/\\n/g, "\n")
    .replace(/\\t/g, "\t")
    .replace(/\\r/g, "")
    .replace(new RegExp("\\\\" + quote, "g"), quote)
    .replace(/\\\\/g, "\\");
}

// Reject code-like captures (only keep genuine single-line UI strings).
function isUiString(s) {
  if (!s || !ARABIC.test(s)) return false;
  if (s.length > 200) return false;
  if (/[\n\r{}<>]|=>|\breturn\b|className/.test(s)) return false;
  return true;
}

function collect(src, found) {
  const reDq = /"((?:[^"\\]|\\.)*)"/g;
  const reSq = /'((?:[^'\\]|\\.)*)'/g;
  const reJsx = />([^<>{}\n]+)</g; // JSX static text between tags
  let m;
  while ((m = reDq.exec(src))) { const v = unescape(m[1], '"').trim(); if (isUiString(v)) found.add(v); }
  while ((m = reSq.exec(src))) { const v = unescape(m[1], "'").trim(); if (isUiString(v)) found.add(v); }
  while ((m = reJsx.exec(src))) { const v = m[1].trim(); if (isUiString(v)) found.add(v); }
}

const files = [];
for (const d of DIRS) {
  const dir = path.join(ROOT, d);
  if (fs.existsSync(dir)) walk(dir, files);
}

const found = new Set();
for (const f of files) collect(stripComments(fs.readFileSync(f, "utf8")), found);

const list = [...found].filter((s) => s && ARABIC.test(s)).sort((a, b) => a.localeCompare(b, "ar"));

const out =
  "// AUTO-GENERATED by scripts/extractI18n.js — do not edit by hand.\n" +
  "// The complete list of translatable source (Arabic) strings in the system.\n" +
  `export const CATALOG: string[] = ${JSON.stringify(list, null, 2)};\n`;

fs.writeFileSync(path.join(ROOT, "lib", "i18nCatalog.ts"), out);
console.log(`i18n catalog: ${list.length} strings from ${files.length} files.`);
